gText_Birch_Welcome::
	.string "Bla bla bla..."
	.string "$"

gText_Birch_Pokemon::
	.string "Bla bla bla..."
	.string "$"

gText_Birch_MainSpeech::
	.string "Bla bla bla..."
	.string "$"

gText_Birch_AndYouAre::
	.string "Who are you?"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "OK. You're {PLAYER}.\n"
	.string "$"

gText_Birch_AreYouReady::
	.string "OK!"
	.string "$"
